### ISSUE TITLE
Could you tell me where can i download this dataset, please？

### ISSUE THREAD

**Issue by graydove** [kang-gnak/eva-dataset#1]

**Comment by kang-gnak** [comment]
Hello, 
this dataset will be released before 12th October here. Thanks for following it.

**Comment by graydove** [comment]
I'm looking forward to it, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kang-gnak/eva-dataset"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 凌晨0:12
收件人:&nbsp;"kang-gnak/eva-dataset"<eva-dataset@noreply.github.com&gt;;
抄送:&nbsp;"太阳"<670332678@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kang-gnak/eva-dataset] Could you tell me where can i download this dataset, please？ (#1)





 
Hello,
 this dataset will be released before 12th October here. Thanks for following it.
