### ISSUE TITLE
Cannot download/extract the image files ?

### ISSUE THREAD

**Issue by SimonCoste** [kang-gnak/eva-dataset#3]
Hi, 
I just downloaded the `eva-dataset`. The `images` folder contains seven files called `EVA_together.zip.00X` for `X=1,...,7`. Those files seem like zip archives, but they seem corrupted - I cannot open them nor extract anything from them. Same thing with the direct download link in the readme file. 
Is there something I'm missing ? 
Best, 
Simon

**Comment by kang-gnak** [comment]
Hi Simon,
Sorry for having this problem. You need to unzip all the files at once. I tried on win7 and it works. Could you please give me a contact email so I can give you a onedrive link to the images?
Best,
